#!/usr/bin/env bash
#  Redirection

sudo apt-get update -y
sudo apt-get -y install nginx
sudo service nginx start
echo "Hello World!" | /var/www/html/index.html

new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.github.com/AdamsGeeky permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

sudo service nginx restart
