#!/usr/bin/env bash
#  Not found page 404

apt-get update -y
apt-get -y install nginx

sudo service nginx start
echo "Hello World!" | /var/www/html/index.html
new_string="server_name _;\n\trewrite ^\/redirect_me ^\/redirect_me https:\/\/www.github.com/AdamsGeeky permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default


echo "Ceci n'est pas une page" | tee /var/www/html/404.html
second_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$second_string/" /etc/nginx/sites-enabled/default

sudo service nginx restart
