#!/usr/bin/env bash
#This script displays Best School and stops at 9 then displays Hi inbetween 
i=1
while [ $i -le 10 ]
do
	echo "Best School"
	if [ $i -eq 9 ];
	then
		echo "Hi"
		break
	fi
	((i++))
done
	echo "Best School"
