#!/usr/bin/env bash
#This script displays 4 and then back luck from china for 4th iteration
#Displays bad luck from japan at 9th iteration
#displays bad luck from italy at 27th iteration
i=1
while [ $i -le 20 ];
do
	echo "$i";
	case $i in
	4) echo "bad luck from China";;
	9) echo "bad luck from Japan";;
	17) echo "bad luck from Italy";
	esac
	((i++))
done
