#!/usr/bin/env bash
#This script displays if a file exist and if not

FILE=school
if [ -e "$FILE" ]; then
	echo "$FILE file exists"
	if [ ! -s "$FILE" ]; then
	       	echo "$FILE file is empty"
		if [ -f "$FILE" ]; then
			echo "$FILE is a regular file"
		fi
	else
		echo "$FILE file is not empty"
		if [ -f "$FILE" ]; then
			echo "$FILE is a regular file"
		fi
	fi
else
	echo "$FILE file does not exist"
fi
